# -*- coding: utf-8 -*-
"""SWE_translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQKTJBI4582A6IwugzXo8ITdvIlphBcW
"""

#imports/reqs
!pip install sentencepiece
!pip install torch
!pip install easynmt[full]

import nltk
from easynmt import EasyNMT

#translation functions; translate to bulgarian nd dutch!
model = EasyNMT('m2m_100_418M')  #using 418M model because it's quicker and still decently accurate.
def translate_to_bulg(text_to_translate):
    translated_text = model.translate(
        text_to_translate,
        source_lang='en',
        target_lang='bg'
    )
    return translated_text

def translate_to_dutch(text_to_translate):
    translated_text = model.translate(
        text_to_translate,
        source_lang='en',
        target_lang='nl'
    )
    return translated_text

#quick examples!
nltk.download('punkt_tab')
example_text = "This is a test."
dutch_result = translate_to_dutch(example_text)
print(f"EN: {example_text}")
print(f"NL: {dutch_result}")

example_text_2 = "This is a test"
dutch_result_2 = translate_to_bulg(example_text_2)
print(f"EN: {example_text_2}")
print(f"BG: {dutch_result_2}")

#more installs/reqs, this is for PDF handling
!pip install PyPDF2
import nltk
nltk.download('punkt')

def translate_pdf(file_path, source, target):
    try:
        full_text = ""
        with open(file_path, 'rb') as f:
            reader = PyPDF2.PdfReader(f)
            for page in reader.pages:
                page_text = page.extract_text()
                if page_text:
                    full_text += page_text.replace('\n', ' ') + " "

        full_text = ' '.join(full_text.split())
        sentences = nltk.sent_tokenize(full_text)
        translated_sentences = model.translate(sentences, source_lang=source, target_lang=target)

        return ' '.join(translated_sentences)
    except FileNotFoundError:
        return "File not found."
    except Exception as e:
        return f"An error occurred: {e}"

#this is pure gepetto
import difflib
from easynmt import EasyNMT

# 🔧 Load translation model once
model = EasyNMT('m2m_100_418M')


cache = {}


# --- Utility: get best match above similarity threshold ---
def get_similar_cached(user_id, text, threshold=0.98):
    """Return (cached_text, cached_translation) if similarity ≥ threshold"""
    if user_id not in cache:
        return None

    best_ratio = 0
    best_key = None

    for cached_sentence in cache[user_id]:
        ratio = difflib.SequenceMatcher(None, text, cached_sentence).ratio()
        if ratio > best_ratio:
            best_ratio = ratio
            best_key = cached_sentence

    if best_ratio >= threshold:
        return best_key, cache[user_id][best_key]

    return None


# --- Add text to cache ---
def update_cache(user_id, text, translation):
    if user_id not in cache:
        cache[user_id] = {}
    cache[user_id][text] = translation


# --- Wrapped translation function with caching ---
def translate_with_cache(user_id, text, target_lang):
    # 1. Try cache lookup
    match = get_similar_cached(user_id, text)
    if match is not None:
        cached_sentence, cached_translation = match
        print(f"🔁 Cache hit for user '{user_id}' (similarity ≥ 98%)")
        return cached_translation

    # 2. If no match, translate normally
    print(f"⚙️ Cache miss → Running model for user '{user_id}'")
    translation = model.translate(text, source_lang='en', target_lang=target_lang)

    # 3. Store result in cache
    update_cache(user_id, text, translation)

    return translation


# --- User-facing functions ---
def translate_to_bulg(user_id, text):
    return translate_with_cache(user_id, text, 'bg')

def translate_to_dutch(user_id, text):
    return translate_with_cache(user_id, text, 'nl')

translate_to_dutch(1, "this is a TEST, test TEST yes a test")

translate_to_dutch(1, "this is a TEST, test TEST yes a test")
translate_to_dutch(2, "this is a TEST, test TEST yes a test")