# -*- coding: utf-8 -*-
"""SWE_translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQKTJBI4582A6IwugzXo8ITdvIlphBcW
"""

#imports/reqs
pip install sentencepiece
pip install torch
pip install easynmt[full]
from nltk import punkt_tab
from easynmt import EasyNMT

#translation functions; translate to bulgarian nd dutch!
model = EasyNMT('m2m_100_418M')  #using 418M model because it's quicker and still decently accurate.
def translate_to_bulg(text_to_translate):
    translated_text = model.translate(
        text_to_translate,
        source_lang='en',
        target_lang='bg'
    )
    return translated_text

def translate_to_dutch(text_to_translate):
    translated_text = model.translate(
        text_to_translate,
        source_lang='en',
        target_lang='nl'
    )
    return translated_text

#quick examples!
example_text = "This is a test."
dutch_result = translate_to_dutch(example_text)
print(f"EN: {example_text}")
print(f"NL: {dutch_result}")

example_text_2 = "This is a test"
dutch_result_2 = translate_to_bulg(example_text_2)
print(f"EN: {example_text_2}")
print(f"BG: {dutch_result_2}")

#more installs/reqs, this is for PDF handling
!pip install PyPDF2
import nltk
nltk.download('punkt')

def translate_pdf(file_path, source, target):
    try:
        full_text = ""
        with open(file_path, 'rb') as f:
            reader = PyPDF2.PdfReader(f)
            for page in reader.pages:
                page_text = page.extract_text()
                if page_text:
                    full_text += page_text.replace('\n', ' ') + " "

        full_text = ' '.join(full_text.split())
        sentences = nltk.sent_tokenize(full_text)
        translated_sentences = model.translate(sentences, source_lang=source, target_lang=target)

        return ' '.join(translated_sentences)
    except FileNotFoundError:
        return "File not found."
    except Exception as e:
        return f"An error occurred: {e}"